---
title: "Bifurcation Project"
author: "U Bhalraam"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Ensure Folders Exist, eval=FALSE, include=FALSE}
Folders_Req <- c("Data", "Normality_Testing", "Table1", "UV_Tables", "MV_Tables", "Cum_Haz_Plots_UnMatched", "Matching_Files", "Cum_Haz_Plots_Matched", "Landmark", "CoxAssumptions", "SensitivityTBif")

for (i in 1:length(Folders_Req)) {

if (!dir.exists(paste0(Folders_Req[i]))){
  dir.create(paste0(Folders_Req[i]))
}else{
  print(paste0(Folders_Req[i], " exists"))
}
}

```

```{r Loading Libraries}
library(MatchIt)
library(tidyverse)
library(haven)
library(readxl)
library(gtsummary)
library(rstatix)
library(ggpubr)
library(doParallel)
library(survival)
library(ggpubr)
library(survminer)
library(gt)

doParallel::registerDoParallel()

theme_gtsummary_journal(journal = "jama")
#> Setting theme `JAMA`
theme_gtsummary_compact()
#> Setting theme `Compact`
```

```{r Inital Handling}
Max_FU_Date = as.POSIXct("2021-03-31", tz = "London/Europe")

data_creat <- read_sav("Data/Updated File for Analysis with Creatinine 22.2.24.sav") %>%
  transmute(
    HospitalNumber = as.numeric(HospitalNumber),
    PlannedProcedureDatex = PlannedProcedureDatex,
    CreatinineLevel = as.numeric(CreatinineLevel)
  )

dataS <- read_sav("Data/File with extra variables including lymphocytes!.sav") %>% select(-CreatinineLevel)

dataS <- left_join(dataS, data_creat, by = c("HospitalNumber", "PlannedProcedureDatex")) 

data_bif <- dataS %>%
  mutate(DEATH = case_when(DEATH > 0 ~ 1,
                           TRUE ~ 0)) %>%
  transmute(Study_ID = as.numeric(STUDY_ID),
            HospitalNumber = as.numeric(HospitalNumber),
            Age = as.numeric(Age),
            Sex = factor(GenderMale1Female2, levels = 1:2, labels = c("Male", "Female")),
            Procedure_Date = as.POSIXct(PlannedProcedureDatex, tz = "London/Europe"),
            Presentation = factor(PresentationSTEMI_1ACS_2STABLE_3, levels = 1:3, labels = c("STEMI", "ACS", "Stable Angina")),
            Multivessel_PCI = factor(MultiVesselPCI, levels = 0:1, labels = c("No", "Yes")),
            BIF_Medina_Classification = factor(BifMedinaClassification.1111110210130114100501060017, levels = 1:7),
            True_Bif = factor(TrueBif1not0, levels = 0:1, labels = c("No", "Yes")),
            #Not sure what the treatment strategy levels are
            Treatment_Strat = factor(Treatmentstrategy.DESsinglevessel1DEStwovessels2DCBsingl, levels = 1:7),
            Frailty_Sc = as.numeric(frailty),
            Frailty_Grp = factor(group, levels = 0:2, labels = c("Not Frail", "Moderately Frail", "Severe Frailty")),
            DCB_DES = fct_relevel(
              factor(DCB_1DES_2, levels = 1:2, labels = c("DCB", "DES")), 
              "DES", "DCB"),
            Duration_Procedure = as.numeric(Durationofprocedure),
            Pressure_Wire = factor(Pressurewire1, levels = 0:1, labels = c("No", "Yes")),
            Imaging = factor(Imaging.IVUS1OCT2, levels = 1:2, labels = c("IVUS", "OCT")),
            ContrastinMLS = as.numeric(ContrastinMLS),
            Fluro_Time_mins = as.numeric(TotalFluoroscopyTimeMinutes),
            Rad_Dose_Area_Product = as.numeric(RadiationDoseAreaProductmGycm2),
            Rad_Skin_Dose = as.numeric(RadiationSkinDosemGy),
            PMHx_Hyperchol = factor(Hypercholesterolaemiafalse0true1, levels = 0:1, labels = c("No", "Yes")),
            PMHx_HTN = factor(Hypertensionfalse0true1, levels = 0:1, labels = c("No", "Yes")),
            PMHx_PVD = factor(Peripheralvasculardiseasefalse0true1, levels = 0:1, labels = c("No", "Yes")),
            PMHx_CVE = factor(Cerebrovasculareventfalse0true1, levels = 0:1, labels = c("No", "Yes")),
            PMHx_MI = factor(MIfalse0true1, levels = 0:1, labels = c("No", "Yes")),
            PMHx_Transplant =  factor(Cardiactransplantfalse0true1, levels = 0:1, labels = c("No", "Yes")),
            PMHx_ValveDx =  factor(Valvularheartdiseasefalse0true1, levels = 0:1, labels = c("No", "Yes")),
            PMHx_PCI = factor(PCIfalse0true1, levels = 0:1, labels = c("No", "Yes")),
            PMHx_AF = factor(AF,  levels = 0:1, labels = c("No", "Yes")),
            PMHx_CABG = factor(CABGfalse0true1, levels = 0:1, labels = c("No", "Yes")),
            PMHx_HF = factor(HeartFailurefalse0true1, levels = 0:1, labels = c("No", "Yes")),
            PMHx_Angina = factor(Anginafalse0true1, levels = 0:1, labels = c("No", "Yes")),
            FHx_CAD = factor(FamilyHistoryofCADfalse0true1, levels = 0:1, labels = c("No", "Yes")),
            PMHx_Asthma = factor(COPDfalse0true1, levels = 0:1, labels = c("No", "Yes")),
            PMHx_COPD = factor(COPDfalse0true1, levels = 0:1, labels = c("No", "Yes")),
            PMHx_DM = factor(Diabetesno0yes1, levels = 0:1, labels = c("No", "Yes")),
            Smok_Stat = factor(smokingstatusneversmoked0currentexsmoker1, levels = 0:1, labels = c("Never Smoked", "Current/Ex Smoker")),
            Creatinine = as.numeric(CreatinineLevel),
            Vessel_Tx = factor(VesseltreatedinnumbersLMS1LAD2LCx3RCA4Graft5, levels = 1:5, labels = c("LMS", "LAD", "LCx", "RCA", "Graft")),
            Heavy_Calc = factor(Heavycalcification, levels = 0:1, labels = c("No", "Yes")),
            Diffuse_Dx = factor(Diffusedisease, levels = 0:1, labels = c("No", "Yes")),
            Tortuosity = factor(Tortuosity, levels = 0:1, labels = c("No", "Yes")),
            denovo_VesselDiam = as.numeric(VesselDiameter),
            denovo_LesionLgth = as.numeric(LesionLength),
            Vessel_GT3mm = factor(case_when(denovo_LesionLgth >30 ~ 1, T ~ 0), levels = 0:1, labels = c("No", "Yes")),
            SB_VesselDiam = as.numeric(SBVesselDiameter),
            SB_LesionLgth = as.numeric(SBLesionLength),
            Hb = as.numeric(Haemaglobin),
            Ferritin = as.numeric(ResultFerritin),
            GFR = parse_number(ResulteGFR),
            Neu = as.numeric(ResultNeutrophils),
            Lym = as.numeric(ResultLymphocytes),
            WBC = Neu + Lym,
            Albumin = as.numeric(Albumin),
            NoreflowSTEMI = fct_explicit_na(factor(NoreflowSTEMIcohort, levels = 1, labels = "Yes"), "No"),
            Anaemia_Acuity = case_when(Sex == "Male" & Hb < 130 ~ 6,
                                  Sex == "Female" & Hb < 120 ~ 6,
                                  TRUE ~ 0),
            Gender_Acuity = case_when(Sex == "Male" ~ 0,
                                      Sex == "Female" ~ 8,
                                      TRUE ~ NA_real_),
            Age_Acuity = case_when(Age < 50 ~ 0,
                                   Age>=50 & Age<60 ~ 3,
                                   Age>=60 & Age<70 ~ 6,
                                   Age>=70 & Age<80 ~ 9,
                                   Age>= 80 ~ 12,
                                   TRUE ~ NA_real_),
            Creatinine_Acuity = case_when(Creatinine < 1.0 ~ 0,
                                          Creatinine>=1.0 & Creatinine<1.2 ~ 2,
                                          Creatinine>=1.2 & Creatinine<1.4 ~ 3,
                                          Creatinine>=1.4 & Creatinine<1.6 ~ 5,
                                          Creatinine>=1.6 & Creatinine<1.8 ~ 6,
                                          Creatinine>=1.8 & Creatinine<2.0 ~ 8,
                                          Creatinine>=2.0 ~ 10,
                                          TRUE ~ NA_real_),
            WBC_Acuity = case_when(WBC < 10 ~ 0,
                                   WBC>=10 & WBC<12 ~ 2,
                                   WBC>=12 & WBC<14 ~ 3,
                                   WBC>=14 & WBC<16 ~ 5,
                                   WBC>=16 & WBC<18 ~ 6,
                                   WBC>=18 & WBC<20 ~ 8,
                                   WBC>=20 ~ 10,
                                   TRUE ~ NA_real_),
            Presentation_Acuity = case_when(TRUE ~ 6),
            Antithrombotic_Acuity = case_when(TRUE ~ 0),
            Acuity_Sc = Anaemia_Acuity + Gender_Acuity + Age_Acuity + Creatinine_Acuity + WBC_Acuity + Presentation_Acuity + Antithrombotic_Acuity,
            Mortality = as.numeric(DEATH),
            Mortality_FU = as.numeric(TotalFU_DAYS),
            Mortality_FU365 = pmin(Mortality_FU, 365),
            Mortality_365 = case_when(Mortality_FU365 < 365 & Mortality == 1 ~ 1,
                                      TRUE ~ 0),
            Mortality_FU30 = pmin(Mortality_FU, 30),
            Mortality_30 = case_when(Mortality_FU30 < 30 & Mortality == 1 ~ 1,
                                      TRUE ~ 0),
            CV_Mortality = as.numeric(CARDIACDEATH),
            CV_Mortality_FU = as.numeric(CD_DAYS),
            CV_Mortality_FU365 = pmin(CV_Mortality_FU, 365),
            CV_Mortality_365 = case_when(CV_Mortality_FU365 < 365 & CV_Mortality == 1 ~ 1,
                                      TRUE ~ 0),
            CV_Mortality_FU30 = pmin(CV_Mortality_FU, 30),
            CV_Mortality_30 = case_when(CV_Mortality_FU30 < 30 & CV_Mortality == 1 ~ 1,
                                      TRUE ~ 0),
            TLR = as.numeric(TLR),
            TLR_FU = as.numeric(TLR_DAYS),
            TLR_FU365 = pmin(TLR_FU, 365),
            TLR_365 = case_when(TLR_FU365 < 365 & TLR == 1 ~ 1,
                                      TRUE ~ 0),
            TLR_FU30 = pmin(TLR_FU, 30),
            TLR_30 = case_when(TLR_FU30 < 30 & TLR == 1 ~ 1,
                                      TRUE ~ 0),
            TLR_MI = as.numeric(TLR_MI),
            TLR_MI_FU = as.numeric(TLR_MI_DAYS),
            TLR_MI_FU365 = pmin(TLR_MI_FU, 365),
            TLR_MI_365 = case_when(TLR_MI_FU365 < 365 & TLR_MI == 1 ~ 1,
                                      TRUE ~ 0),
            TLR_MI_FU30 = pmin(TLR_MI_FU, 30),
            TLR_MI_30 = case_when(TLR_MI_FU30 < 30 & TLR_MI == 1 ~ 1,
                                      TRUE ~ 0),
            Composite = as.numeric(Compositeendpoint),
            Composite_FU = as.numeric(Compositeendpoint_DAYS),
            Composite_FU365 = pmin(Composite_FU, 365),
            Composite_365 = case_when(Composite_FU < 365 & Composite == 1 ~ 1,
                                      TRUE ~ 0),
            Composite_FU30 = pmin(Composite_FU, 30),
            Composite_30 = case_when(Composite_FU30 < 30 & Composite == 1 ~ 1,
                                      TRUE ~ 0),
            Composite_wMort = case_when(Mortality == 1 ~ 1,
                                  CV_Mortality == 1 ~ 1,
                                  TLR == 1 ~ 1,
                                  TLR_MI == 1 ~ 1,
                                  TRUE ~ 0),
            Composite_wMort_FU = case_when(Composite_wMort == T ~ pmin(Mortality_FU, CV_Mortality_FU, TLR_FU, TLR_MI_FU),
                                     TRUE ~ TotalFU_DAYS),
            Composite_wMort_FU365 = pmin(Composite_wMort_FU, 365),
            Composite_wMort_365 = case_when(Composite_wMort_FU365 < 365 & Composite_wMort == 1 ~ 1,
                                      TRUE ~ 0),
            Composite_wMort_FU30 = pmin(Composite_wMort_FU, 30),
            Composite_wMort_30 = case_when(Composite_wMort_FU30 < 30 & Composite_wMort == 1 ~ 1,
                                      TRUE ~ 0)
  )

#set.seed(234)
#patients_to_remove <- data_bif %>%
#  filter(DCB_DES == "DES") %>%
#  sample_n(53) %>% 
#  select(HospitalNumber)

#data_bif <- data_bif %>%
#  anti_join(patients_to_remove, by = "HospitalNumber")

levels(data_bif$Vessel_Tx)[levels(data_bif$Vessel_Tx)=='Graft'] <- NA

data_bif_swap <- data_bif %>%
  mutate(DCB_DES = fct_rev(DCB_DES))

```

```{r Normality Testing}
NumVar <- data_bif %>%
  select(where(is.numeric), -ends_with("Acuity")) %>%
  names() %>%
  syms()

Shapiro_Test <- data_bif %>%
  shapiro_test(vars = NumVar) 

NormallyDistVars <- Shapiro_Test %>%
  filter(p >= 0.05) %>%
  pull(variable) 

NonNormallyDistVars <- Shapiro_Test %>%
  filter(p < 0.05) %>%
  pull(variable) 

non_normal_densityplots <- list()
non_normal_qqplots <- list()

for (i in 1:length(NonNormallyDistVars)) {
  
  non_normal_densityplots[[i]] <- data_bif %>%
  ggdensity(NonNormallyDistVars[i], fill = "lightgray") 
  
  non_normal_qqplots[[i]] <- data_bif %>%
  ggqqplot(NonNormallyDistVars[i], fill = "lightgray") 
  
}

ggexport(plotlist = non_normal_densityplots, filename = "Normality_Testing/density.pdf",
         nrow = 2, ncol = 2)

ggexport(plotlist = non_normal_qqplots, filename = "Normality_Testing/qq.pdf",
         nrow = 2, ncol = 2)

NormallyDistVars <-  c() #No Normally distributed variables.
```

```{r Table 1}

data_Table <- data_bif #%>%
  #select(-ends_with())

Baseline_T <- tbl_summary(data_Table,
            by = DCB_DES) %>%
  add_p() %>%
  bold_p() %>%
  add_overall() %>%
  gtsummary::separate_p_footnotes() %>%
  as_gt() 

gtsave(Baseline_T, "Table1/BaselineT.html")
```

```{r Univariate Tables (To inform variable selection)}
UV_T <- list()

Outcomes <- c("Mortality", "CV_Mortality", "TLR", "TLR_MI", "Composite", "Composite_wMort")
Followups <- c("Mortality_FU", "CV_Mortality_FU", "TLR_FU", "TLR_MI_FU", "Composite_FU", "Composite_wMort_FU")

library(doFuture)
registerDoFuture()
plan(multisession)

foreach(i=1:6, .packages = c("foreach", "tidyverse", "gtsummary")) %dopar% {
  
setwd("/home/rstudio/Encrypted-Data/R/R Projects/Bifurcation_Project")
    
theme_gtsummary_journal(journal = "jama")
#> Setting theme `JAMA`
theme_gtsummary_compact()
#> Setting theme `Compact`

.GlobalEnv$UV_T[[i]] <-  gtsummary::tbl_uvregression(data_bif_swap,
                 method = survival::coxph,
                 y = survival::Surv(time = !!sym(Followups[i]), event = !!sym(Outcomes[i])),
                 exponentiate = T,
                 include = c(Age, Sex, Presentation, Multivessel_PCI, BIF_Medina_Classification, True_Bif, Treatment_Strat, Frailty_Sc, Frailty_Grp, DCB_DES, Duration_Procedure, Pressure_Wire, Imaging, ContrastinMLS, Fluro_Time_mins, Rad_Dose_Area_Product, Rad_Skin_Dose, PMHx_Hyperchol, PMHx_HTN, PMHx_PVD, PMHx_CVE, PMHx_MI, PMHx_PCI, PMHx_CABG, PMHx_HF, PMHx_Angina, FHx_CAD, PMHx_Asthma, PMHx_COPD, PMHx_DM, Smok_Stat, Creatinine, Heavy_Calc, Diffuse_Dx, Tortuosity, denovo_LesionLgth, Vessel_GT3mm, SB_VesselDiam, SB_LesionLgth)) %>%
  gtsummary::modify_header(label = paste0("**",Outcomes[i],"**", " (Univariate)")) %>%
  gtsummary::bold_p() %>%
  gtsummary::as_gt()

gt::gtsave(.GlobalEnv$UV_T[[i]], paste0("UV_Tables/" , Outcomes[i], "_UV.html"))

}
```

```{r CumHaz Charts}
fit1<- survfit(Surv(Mortality_FU, Mortality) ~ DCB_DES, data = data_bif)
plot1 <- ggsurvplot(fit1, fun = "cumhaz", pval = TRUE, conf.int = TRUE,
           risk.table = T, risk.table.y.text.col = TRUE, ylim=c(0,0.3), xscale="d_y", legend.labs = c("DES", "DCB"), xlab = "Years Since Index Procedure", ylab = "Probability of All-Cause Mortality", palette = c("#fba30c", "#0077b8"), theme = "lancet", break.time.by	= 365.25, pval.coord = c(0,0.1), legend.title = "") 

fit2<- survfit(Surv(CV_Mortality_FU, CV_Mortality) ~ DCB_DES, data = data_bif)
plot2 <- ggsurvplot(fit2, fun = "cumhaz", pval = TRUE, conf.int = TRUE,
           risk.table = T, risk.table.y.text.col = TRUE, ylim=c(0,0.3), xscale="d_y", legend.labs = c("DES", "DCB"), xlab = "Years Since Index Procedure", ylab = "Probability of Cardiovascular Mortality", palette = c("#fba30c", "#0077b8"), theme = "lancet", break.time.by	= 365.25, pval.coord = c(0,0.1), legend.title = "")  

fit3<- survfit(Surv(TLR_FU, TLR) ~ DCB_DES, data = data_bif)
plot3 <- ggsurvplot(fit3, fun = "cumhaz", pval = TRUE, conf.int = TRUE,
           risk.table = T, risk.table.y.text.col = TRUE, ylim=c(0,0.3), xscale="d_y", legend.labs = c("DES", "DCB"), xlab = "Years Since Index Procedure", ylab = "Probability of Incurring TLR", palette = c("#fba30c", "#0077b8"), theme = "lancet", break.time.by	= 365.25, pval.coord = c(0,0.1), legend.title = "")  

fit4<- survfit(Surv(TLR_MI_FU, TLR_MI) ~ DCB_DES, data = data_bif)
plot4 <- ggsurvplot(fit4, fun = "cumhaz", pval = TRUE, conf.int = TRUE,
           risk.table = T, risk.table.y.text.col = TRUE, ylim=c(0,0.3), xscale="d_y", legend.labs = c("DES", "DCB"), xlab = "Years Since Index Procedure", ylab = "Probability of Incurring Target Lesion MI", palette = c("#fba30c", "#0077b8"), theme = "lancet", break.time.by	= 365.25, pval.coord = c(0,0.1), legend.title = "")  

fit5<- survfit(Surv(Composite_FU, Composite) ~ DCB_DES, data = data_bif)
plot5 <- ggsurvplot(fit5, fun = "cumhaz", pval = TRUE, conf.int = TRUE,
           risk.table = T, risk.table.y.text.col = TRUE, ylim=c(0,0.3), xscale="d_y", legend.labs = c("DES", "DCB"), xlab = "Years Since Index Procedure", ylab = "Probability of Incurring Composite Endpoint", palette = c("#fba30c", "#0077b8"), theme = "lancet", break.time.by	= 365.25, pval.coord = c(0,0.1), legend.title = "")

fit6 <- survfit(Surv(Composite_wMort_FU, Composite_wMort) ~ DCB_DES, data = data_bif)
plot6 <- ggsurvplot(fit6, fun = "cumhaz", pval = TRUE, conf.int = TRUE,
           risk.table = T, risk.table.y.text.col = TRUE, ylim=c(0,0.35), xscale="d_y", legend.labs = c("DES", "DCB"), xlab = "Years Since Index Procedure", ylab = "Probability of Incurring Composite Endpoint w/Mort", palette = c("#fba30c", "#0077b8"), theme = "lancet", break.time.by	= 365.25, pval.coord = c(0,0.1), legend.title = "")

cairo_pdf(filename = "Cum_Haz_Plots_UnMatched/CumHazPlots.pdf",
         width = 6, height = 6, onefile = T)
print(plot1, newpage = F)
print(plot2)
print(plot3)
print(plot4)
print(plot5)
print(plot6)
dev.off()
```

```{r Searching for the variables to PS Match for}
PS_Variable_Search <- data_bif %>%
  drop_na(DCB_DES) %>%
  select(-Study_ID, -HospitalNumber, -Imaging, -PMHx_Transplant)

gtsummary::tbl_uvregression(PS_Variable_Search,
                 method = glm,
                 method.args = list(family = binomial),
                 y = DCB_DES,
                 exponentiate = T) %>%
  modify_header(label = paste0("**",Outcomes[i],"**", " (Univariate)")) %>%
  bold_p() %>%
  as_gt()

PS_Variables = c("DCB_DES", "Presentation", "BIF_Medina_Classification", "True_Bif", "Duration_Procedure", "ContrastinMLS", "Rad_Skin_Dose", "PMHx_MI", "PMHx_PCI", "PMHx_AF", "Heavy_Calc", "Diffuse_Dx", "Tortuosity","Vessel_Tx", "denovo_VesselDiam", "denovo_LesionLgth")
```

```{r PS Matching (All)}
nCores <- detectCores() - 1

data_ps_bif <- data_bif_swap %>%
  select(DCB_DES, Age, Sex, Presentation, True_Bif, PMHx_MI, PMHx_PCI, PMHx_AF, PMHx_HTN, PMHx_PVD, PMHx_CVE, Heavy_Calc, Diffuse_Dx, Tortuosity, PMHx_DM, Creatinine, denovo_VesselDiam, denovo_LesionLgth, Vessel_Tx, Mortality, CV_Mortality, TLR, TLR_MI, Composite, Composite_wMort, Mortality_FU, CV_Mortality_FU, TLR_FU, TLR_MI_FU, Composite_FU, Composite_wMort_FU) %>%
  mutate(DCB_DES = fct_relevel(DCB_DES,c("DES", "DCB"))) %>%
  drop_na(1:19)

set.seed(1125)

match.it <- matchit(DCB_DES ~ Age+ Sex+ True_Bif+ PMHx_PCI+ PMHx_AF+ Creatinine, data = data_ps_bif, method="genetic", replace = T,  pop.size = 1000, cluster = parallel::makeCluster(nCores)) #Full matching technique

a <- summary(match.it)

df.match1 <- get_matches(match.it)
df.matchid <- get_matches(match.it) %>% select(id) %>% mutate(id = as.numeric(id))

df.match_All <- df.match1

df.match_Full <- inner_join(data_bif, df.match1, by = names(df.match1)[4:32])
```

```{r Extract ID numbers}
all_ids <- data_ps_bif %>%
  mutate(id = 1:nrow(data_ps_bif)) %>%
  pull(id)

matched_ids <- df.match_Full$id

excluded_ids <- setdiff(all_ids, matched_ids)

data_ps_bif <- data_ps_bif %>%
  mutate(id = 1:nrow(data_ps_bif))

excluded_people <- filter(data_ps_bif, id %in% excluded_ids) %>% mutate(inclusion = 1)
included_people <- filter(data_ps_bif, id %in% matched_ids) %>% mutate(inclusion = 0)

combined_table <- bind_rows(excluded_people, included_people) %>% mutate(inclusion = factor(inclusion, levels=0:1, labels = c("Matched", "Unmatched")))

Baseline_T_incexc <- tbl_summary(combined_table,
            by = inclusion, include = -id) %>%
  add_p() %>%
  bold_p() %>%
  gtsummary::separate_p_footnotes() %>%
  as_gt() 

gtsave(Baseline_T_incexc, "Table1/BaselineT_incexc.html")

```

```{r Prove no missing differences}
data_ps_bif_miss <- data_bif %>%
  select(HospitalNumber, DCB_DES, Age, Sex, Presentation, True_Bif, PMHx_MI, PMHx_PCI, PMHx_AF, Heavy_Calc, Diffuse_Dx, Tortuosity, PMHx_DM, Creatinine, denovo_VesselDiam, denovo_LesionLgth, Mortality, CV_Mortality, TLR, TLR_MI, Composite, Composite_wMort, Mortality_FU, CV_Mortality_FU, TLR_FU, TLR_MI_FU, Composite_FU, Composite_wMort_FU) %>%
  mutate(missing = 1) #%>% filter(DCB_DES == "DCB")

data_ps_bif_nomiss <- data_bif %>%
  select(HospitalNumber, DCB_DES, Age, Sex, Presentation, True_Bif, PMHx_MI, PMHx_PCI, PMHx_AF, Heavy_Calc, Diffuse_Dx, Tortuosity, PMHx_DM, Creatinine, denovo_VesselDiam, denovo_LesionLgth, Mortality, CV_Mortality, TLR, TLR_MI, Composite, Composite_wMort, Mortality_FU, CV_Mortality_FU, TLR_FU, TLR_MI_FU, Composite_FU, Composite_wMort_FU) %>%
  drop_na(1:15) %>%
  mutate(missingno = 1) # %>% filter(DCB_DES == "DCB")

data_ps_bif_diff <- anti_join(data_ps_bif_miss, data_ps_bif_nomiss, by = c("HospitalNumber", "DCB_DES", "Age", "Sex", "Presentation", "True_Bif", "PMHx_MI", "PMHx_PCI", "PMHx_AF", "Heavy_Calc", "Diffuse_Dx", "Tortuosity", "PMHx_DM", "Creatinine", "denovo_VesselDiam", "denovo_LesionLgth", "Mortality", "CV_Mortality", "TLR", "TLR_MI", "Composite", "Composite_wMort", "Mortality_FU", "CV_Mortality_FU", "TLR_FU", "TLR_MI_FU", "Composite_FU", "Composite_wMort_FU")) %>% mutate(missingno = 2)


data_ps_bif_missanalysis <- bind_rows(data_ps_bif_diff, data_ps_bif_nomiss) %>%
  mutate(missing = factor(missingno, levels = 1:2, labels = c("Included", "Missing Data")))

Baseline_T_missing <- tbl_summary(data_ps_bif_missanalysis,
            by = missing, include = c(-"HospitalNumber", -"missingno")) %>%
  add_p() %>%
  bold_p() %>%
  gtsummary::separate_p_footnotes() %>%
  as_gt() 

gtsave(Baseline_T_missing, "Table1/BaselineT_missing.html")
```

```{r Table1 for Matched Set}
data_Table <- df.match_Full %>%
  select(-id)

Baseline_T <- tbl_summary(data_Table,
            by = DCB_DES, include = -subclass) %>%
  add_p() %>%
  bold_p() %>%
  add_overall() %>%
  gtsummary::separate_p_footnotes() %>%
  as_gt() 

gtsave(Baseline_T, "Table1/PS_BaselineT.html")

```

```{r UV_T for matched}

library(coxme)

data_bif_mv1 <- df.match_All %>%
  select(DCB_DES, Age, Sex, Presentation, True_Bif, PMHx_MI, PMHx_PCI, PMHx_AF, Heavy_Calc, Diffuse_Dx, Tortuosity, Tortuosity, denovo_VesselDiam, denovo_LesionLgth, Vessel_Tx, Mortality, Mortality_FU, CV_Mortality, CV_Mortality_FU, TLR, TLR_FU, TLR_MI, TLR_MI_FU, Composite, Composite_FU, Composite_wMort, Composite_wMort_FU, subclass) %>%
  drop_na() %>%
  mutate(subclass = as.numeric(subclass)) %>%
  mutate(Presentation = fct_relevel(Presentation, c("Stable Angina", "ACS", "STEMI")))

res.cox_CVMortality <- coxme(Surv(time = CV_Mortality_FU, event = CV_Mortality) ~ DCB_DES + (1|subclass), data = data_bif_mv1)

res.cox_TLR <- coxme(Surv(time = TLR_FU, event = TLR) ~ DCB_DES + (1|subclass), data = data_bif_mv1)

res.cox_TLRMI <- coxme(Surv(time = TLR_MI_FU, event = TLR_MI) ~ DCB_DES + (1|subclass), data = data_bif_mv1)

res.cox_Comp <- coxme(Surv(time = Composite_FU, event = Composite) ~ DCB_DES + (1|subclass), data = data_bif_mv1)


A <- gtsummary::tbl_regression(res.cox_Comp, exponentiate = T) %>% as_gt()
B <- gtsummary::tbl_regression(res.cox_TLR, exponentiate = T) %>% as_gt()
C <- gtsummary::tbl_regression(res.cox_TLRMI, exponentiate = T) %>% as_gt()
D <- gtsummary::tbl_regression(res.cox_CVMortality, exponentiate = T) %>% as_gt()

gtsave(A, "UV_Tables/Composite_Matched_UV.html")
gtsave(B, "UV_Tables/TLR_Matched_UV.html")
gtsave(C, "UV_Tables/TLRMI_Matched_UV.html")
gtsave(D, "UV_Tables/CVMortality_Matched_UV.html")

```


```{r CumHaz Charts_PS_Match}
fit1<- survfit(Surv(Mortality_FU, Mortality) ~ DCB_DES, data = df.match_All)
plot1 <- ggsurvplot(fit1, fun = "cumhaz", pval = TRUE, conf.int = TRUE,
           risk.table = T, risk.table.y.text.col = TRUE, ylim=c(0,0.3), xscale="d_y", legend.labs = c("DES", "DCB"), xlab = "Years Since Index Procedure", ylab = "Probability of All-Cause Mortality", palette = c("#fba30c", "#0077b8"), theme = "lancet", break.time.by	= 365.25, pval.coord = c(0,0.1), legend.title = "") 

fit2<- survfit(Surv(CV_Mortality_FU, CV_Mortality) ~ DCB_DES, data = df.match_All)
plot2 <- ggsurvplot(fit2, fun = "cumhaz", pval = TRUE, conf.int = TRUE,
           risk.table = T, risk.table.y.text.col = TRUE, ylim=c(0,0.3), xscale="d_y", legend.labs = c("DES", "DCB"), xlab = "Years Since Index Procedure", ylab = "Probability of Cardiovascular Mortality", palette = c("#fba30c", "#0077b8"), theme = "lancet", break.time.by	= 365.25, pval.coord = c(0,0.1), legend.title = "")  

fit3<- survfit(Surv(TLR_FU, TLR) ~ DCB_DES, data = df.match_All)
plot3 <- ggsurvplot(fit3, fun = "cumhaz", pval = TRUE, conf.int = TRUE,
           risk.table = T, risk.table.y.text.col = TRUE, ylim=c(0,0.3), xscale="d_y", legend.labs = c("DES", "DCB"), xlab = "Years Since Index Procedure", ylab = "Probability of Incurring TLR", palette = c("#fba30c", "#0077b8"), theme = "lancet", break.time.by	= 365.25, pval.coord = c(0,0.15), legend.title = "")  

fit4<- survfit(Surv(TLR_MI_FU, TLR_MI) ~ DCB_DES, data = df.match_All)
plot4 <- ggsurvplot(fit4, fun = "cumhaz", pval = TRUE, conf.int = TRUE,
           risk.table = T, risk.table.y.text.col = TRUE, ylim=c(0,0.3), xscale="d_y", legend.labs = c("DES", "DCB"), xlab = "Years Since Index Procedure", ylab = "Probability of Incurring Target Lesion MI", palette = c("#fba30c", "#0077b8"), theme = "lancet", break.time.by	= 365.25, pval.coord = c(0,0.1), legend.title = "")  

fit5<- survfit(Surv(Composite_FU, Composite) ~ DCB_DES, data = df.match_All)
plot5 <- ggsurvplot(fit5, fun = "cumhaz", pval = TRUE, conf.int = TRUE,
           risk.table = T, risk.table.y.text.col = TRUE, ylim=c(0,0.3), xscale="d_y", legend.labs = c("DES", "DCB"), xlab = "Years Since Index Procedure", ylab = "Probability of Incurring Composite Endpoint", palette = c("#fba30c", "#0077b8"), theme = "lancet", break.time.by	= 365.25, pval.coord = c(0,0.15), legend.title = "")

fit6 <- survfit(Surv(Composite_wMort_FU, Composite_wMort) ~ DCB_DES, data = df.match_All)
plot6 <- ggsurvplot(fit6, fun = "cumhaz", pval = TRUE, conf.int = TRUE,
           risk.table = T, risk.table.y.text.col = TRUE, ylim=c(0,0.35), xscale="d_y", legend.labs = c("DES", "DCB"), xlab = "Years Since Index Procedure", ylab = "Probability of Incurring Composite Endpoint w/Mort", palette = c("#fba30c", "#0077b8"), theme = "lancet", break.time.by	= 365.25, pval.coord = c(0,0.15), legend.title = "")

cairo_pdf(filename = "Cum_Haz_Plots_Matched/CumHazPlots.pdf",
         width = 6, height = 6, onefile = T)
print(plot1, newpage = F)
print(plot2)
print(plot3)
print(plot4)
print(plot5)
print(plot6)
dev.off()
```

```{r Landmark Analysis}
df.match_Mort2 <- df.match_All %>%
  filter(Mortality_FU >= 365) %>%
  mutate(Mortality_FU = Mortality_FU - 365)
  
df.match_CVMort2 <- df.match_All %>%
  filter(CV_Mortality_FU >= 365) %>%
  mutate(CV_Mortality_FU = CV_Mortality_FU - 365)

df.match_TLR2 <- df.match_All %>%
  filter(TLR_FU >= 365) %>%
  mutate(TLR_FU = TLR_FU - 365)

df.match_TLR_MI2 <- df.match_All %>%
  filter(TLR_MI_FU >= 365) %>%
  mutate(TLR_MI_FU = TLR_MI_FU - 365)

df.match_Comp2 <- df.match_All %>%
  filter(Composite_FU >= 365) %>%
  mutate(Composite_FU = Composite_FU - 365)

df.match_CompwMort2 <- df.match_All %>%
  filter(Composite_wMort_FU >= 365) %>%
  mutate(Composite_wMort_FU = Composite_wMort_FU - 365)

#This part uses all the *1 dfs.

fit1<- survfit(Surv(Mortality_FU, Mortality) ~ DCB_DES, data = df.match_Mort2)
plot1 <- ggsurvplot(fit1, fun = "cumhaz", pval = TRUE, conf.int = TRUE,
           risk.table = T, risk.table.y.text.col = TRUE, ylim=c(0,0.3), xscale="d_y", legend.labs = c("DES", "DCB"), xlab = "Years Since 1-Year Landmark", ylab = "Probability of All-Cause Mortality", palette = c("#fba30c", "#0077b8"), theme = "lancet", break.time.by	= 365.25, pval.coord = c(0,0.1), legend.title = "") 

fit2<- survfit(Surv(CV_Mortality_FU, CV_Mortality) ~ DCB_DES, data = df.match_CVMort2)
plot2 <- ggsurvplot(fit2, fun = "event", pval = TRUE, conf.int = TRUE,
           risk.table = T, risk.table.y.text.col = TRUE, ylim=c(0,0.3), xscale="d_y", legend.labs = c("DES", "DCB"), xlab = "Years Since 1-Year Landmark", ylab = "Probability of Cardiovascular Mortality", palette = c("#fba30c", "#0077b8"), theme = "lancet", break.time.by	= 365.25, pval.coord = c(0,0.1), legend.title = "")  

fit3<- survfit(Surv(TLR_FU, TLR) ~ DCB_DES, data = df.match_TLR2)
plot3 <- ggsurvplot(fit3, fun = "event", pval = TRUE, conf.int = TRUE,
           risk.table = T, risk.table.y.text.col = TRUE, ylim=c(0,0.3), xscale="d_y", legend.labs = c("DES", "DCB"), xlab = "Years Since 1-Year Landmark", ylab = "Probability of Incurring TLR", palette = c("#fba30c", "#0077b8"), theme = "lancet", break.time.by	= 365.25, pval.coord = c(0,0.1), legend.title = "")  

fit4<- survfit(Surv(TLR_MI_FU, TLR_MI) ~ DCB_DES, data = df.match_TLR_MI2)
plot4 <- ggsurvplot(fit4, fun = "event", pval = TRUE, conf.int = TRUE,
           risk.table = T, risk.table.y.text.col = TRUE, ylim=c(0,0.3), xscale="d_y", legend.labs = c("DES", "DCB"), xlab = "Years Since 1-Year Landmark", ylab = "Probability of Incurring Target Lesion MI", palette = c("#fba30c", "#0077b8"), theme = "lancet", break.time.by	= 365.25, pval.coord = c(0,0.1), legend.title = "")  

fit5<- survfit(Surv(Composite_FU, Composite) ~ DCB_DES, data = df.match_Comp2)
plot5 <- ggsurvplot(fit5, fun = "event", pval = TRUE, conf.int = TRUE,
           risk.table = T, risk.table.y.text.col = TRUE, ylim=c(0,0.3), xscale="d_y", legend.labs = c("DES", "DCB"), xlab = "Years Since 1-Year Landmark", ylab = "Probability of Incurring Composite Endpoint", palette = c("#fba30c", "#0077b8"), theme = "lancet", break.time.by	= 365.25, pval.coord = c(0,0.15), legend.title = "")

fit6 <- survfit(Surv(Composite_wMort_FU, Composite_wMort) ~ DCB_DES, data = df.match_CompwMort2)
plot6 <- ggsurvplot(fit6, fun = "event", pval = TRUE, conf.int = TRUE,
           risk.table = T, risk.table.y.text.col = TRUE, ylim=c(0,0.35), xscale="d_y", legend.labs = c("DES", "DCB"), xlab = "Years Since 1-Year Landmark", ylab = "Probability of Incurring Composite Endpoint w/Mort", palette = c("#fba30c", "#0077b8"), theme = "lancet", break.time.by	= 365.25, pval.coord = c(0,0.15), legend.title = "")

cairo_pdf(filename = "Landmark/CumHazPlots.pdf",
         width = 6, height = 6, onefile = T)
print(plot1, newpage = F)
print(plot2)
print(plot3)
print(plot4)
print(plot5)
print(plot6)
dev.off()

df.Match_360 <- df.match_All %>%
  mutate(   Mortality_FU365 = pmin(Mortality_FU, 365),
            Mortality_365 = case_when(Mortality_FU365 < 365 & Mortality == 1 ~ 1,
                                      TRUE ~ 0),
            CV_Mortality_FU365 = pmin(CV_Mortality_FU, 365),
            CV_Mortality_365 = case_when(CV_Mortality_FU365 < 365 & CV_Mortality == 1 ~ 1,
                                      TRUE ~ 0),
            TLR_FU365 = pmin(TLR_FU, 365),
            TLR_365 = case_when(TLR_FU365 < 365 & TLR == 1 ~ 1,
                                      TRUE ~ 0),
            TLR_MI_FU365 = pmin(TLR_MI_FU, 365),
            TLR_MI_365 = case_when(TLR_MI_FU365 < 365 & TLR_MI == 1 ~ 1,
                                      TRUE ~ 0),
            Composite_FU365 = pmin(Composite_FU, 365),
            Composite_365 = case_when(Composite_FU < 365 & Composite == 1 ~ 1,
                                      TRUE ~ 0),
            Composite_wMort_FU365 = pmin(Composite_wMort_FU, 365),
            Composite_wMort_365 = case_when(Composite_wMort_FU365 < 365 & Composite_wMort == 1 ~ 1,
                                      TRUE ~ 0)
  )

fit1<- survfit(Surv(Mortality_FU365, Mortality_365) ~ DCB_DES, data = df.Match_360)
plot1 <- ggsurvplot(fit1, fun = "cumhaz", pval = TRUE, conf.int = TRUE,
           risk.table = T, risk.table.y.text.col = TRUE, ylim=c(0,0.3), xlim=c(0,365), xscale="d_m", legend.labs = c("DES", "DCB"), xlab = "Months Until 1-Year Landmark", ylab = "Probability of All-Cause Mortality", palette = c("#fba30c", "#0077b8"), theme = "lancet", break.time.by	= 30.4375, pval.coord = c(0,0.1), legend.title = "") 

fit2<- survfit(Surv(CV_Mortality_FU365, CV_Mortality_365) ~ DCB_DES, data = df.Match_360)
plot2 <- ggsurvplot(fit2, fun = "event", pval = TRUE, conf.int = TRUE,
           risk.table = T, risk.table.y.text.col = TRUE, ylim=c(0,0.3), xlim=c(0,365), xscale="d_m", legend.labs = c("DES", "DCB"), xlab = "Months Until 1-Year Landmark", ylab = "Probability of Cardiovascular Mortality", palette = c("#fba30c", "#0077b8"), theme = "lancet", break.time.by	= 30.4375, pval.coord = c(0,0.1), legend.title = "")  

fit3<- survfit(Surv(TLR_FU365, TLR_365) ~ DCB_DES, data = df.Match_360)
plot3 <- ggsurvplot(fit3, fun = "event", pval = TRUE, conf.int = TRUE,
           risk.table = T, risk.table.y.text.col = TRUE, ylim=c(0,0.3), xlim=c(0,365), xscale="d_m", legend.labs = c("DES", "DCB"), xlab = "Months Until 1-Year Landmark", ylab = "Probability of Incurring TLR", palette = c("#fba30c", "#0077b8"), theme = "lancet", break.time.by	= 30.4375, pval.coord = c(0,0.1), legend.title = "")  

fit4<- survfit(Surv(TLR_MI_FU365, TLR_MI_365) ~ DCB_DES, data = df.Match_360)
plot4 <- ggsurvplot(fit4, fun = "event", pval = TRUE, conf.int = TRUE,
           risk.table = T, risk.table.y.text.col = TRUE, ylim=c(0,0.3), xlim=c(0,365), xscale="d_m", legend.labs = c("DES", "DCB"), xlab = "Months Until 1-Year Landmark", ylab = "Probability of Incurring Target Lesion MI", palette = c("#fba30c", "#0077b8"), theme = "lancet", break.time.by	= 30.4375, pval.coord = c(0,0.1), legend.title = "")  

fit5<- survfit(Surv(Composite_FU365, Composite_365) ~ DCB_DES, data = df.Match_360)
plot5 <- ggsurvplot(fit5, fun = "event", pval = TRUE, conf.int = TRUE,
           risk.table = T, risk.table.y.text.col = TRUE, ylim=c(0,0.3), xlim=c(0,365), xscale="d_m", legend.labs = c("DES", "DCB"), xlab = "Months Until 1-Year Landmark", ylab = "Probability of Incurring Composite Endpoint", palette = c("#fba30c", "#0077b8"), theme = "lancet", break.time.by	= 30.4375, pval.coord = c(0,0.15), legend.title = "")

fit6 <- survfit(Surv(Composite_wMort_FU365, Composite_wMort_365) ~ DCB_DES, data = df.Match_360)
plot6 <- ggsurvplot(fit6, fun = "event", pval = TRUE, conf.int = TRUE,
           risk.table = T, risk.table.y.text.col = TRUE, ylim=c(0,0.35), xlim=c(0,365), xscale="d_m", legend.labs = c("DES", "DCB"), xlab = "Months Until 1-Year Landmark", ylab = "Probability of Incurring Composite Endpoint w/Mort", palette = c("#fba30c", "#0077b8"), theme = "lancet", break.time.by	= 30.4375, pval.coord = c(0,0.15), legend.title = "")

cairo_pdf(filename = "Landmark/CumHazPlots_LT365.pdf",
         width = 7, height = 6, onefile = T)
print(plot1, newpage = F)
print(plot2)
print(plot3)
print(plot4)
print(plot5)
print(plot6)
dev.off()
```

```{r Sensitivity Analysis}

df.match_TBif <- df.match_All %>%
  filter(True_Bif == "Yes")

fit1<- survfit(Surv(Mortality_FU, Mortality) ~ DCB_DES, data = df.match_TBif)
plot1 <- ggsurvplot(fit1, fun = "cumhaz", pval = TRUE, conf.int = TRUE,
           risk.table = T, risk.table.y.text.col = TRUE, ylim=c(0,0.3), xscale="d_y", legend.labs = c("DES", "DCB"), xlab = "Years Since Index Procedure", ylab = "Probability of All-Cause Mortality", palette = c("#fba30c", "#0077b8"), theme = "lancet", break.time.by	= 365.25, pval.coord = c(0,0.1), legend.title = "") 

fit2<- survfit(Surv(CV_Mortality_FU, CV_Mortality) ~ DCB_DES, data = df.match_TBif)
plot2 <- ggsurvplot(fit2, fun = "cumhaz", pval = TRUE, conf.int = TRUE,
           risk.table = T, risk.table.y.text.col = TRUE, ylim=c(0,0.3), xscale="d_y", legend.labs = c("DES", "DCB"), xlab = "Years Since Index Procedure", ylab = "Probability of Cardiovascular Mortality", palette = c("#fba30c", "#0077b8"), theme = "lancet", break.time.by	= 365.25, pval.coord = c(0,0.1), legend.title = "")  

fit3<- survfit(Surv(TLR_FU, TLR) ~ DCB_DES, data = df.match_TBif)
plot3 <- ggsurvplot(fit3, fun = "cumhaz", pval = TRUE, conf.int = TRUE,
           risk.table = T, risk.table.y.text.col = TRUE, ylim=c(0,0.3), xscale="d_y", legend.labs = c("DES", "DCB"), xlab = "Years Since Index Procedure", ylab = "Probability of Incurring TLR", palette = c("#fba30c", "#0077b8"), theme = "lancet", break.time.by	= 365.25, pval.coord = c(0,0.1), legend.title = "")  

fit4<- survfit(Surv(TLR_MI_FU, TLR_MI) ~ DCB_DES, data = df.match_TBif)
plot4 <- ggsurvplot(fit4, fun = "cumhaz", pval = TRUE, conf.int = TRUE,
           risk.table = T, risk.table.y.text.col = TRUE, ylim=c(0,0.3), xscale="d_y", legend.labs = c("DES", "DCB"), xlab = "Years Since Index Procedure", ylab = "Probability of Incurring Target Lesion MI", palette = c("#fba30c", "#0077b8"), theme = "lancet", break.time.by	= 365.25, pval.coord = c(0,0.1), legend.title = "")  

fit5<- survfit(Surv(Composite_FU, Composite) ~ DCB_DES, data = df.match_TBif)
plot5 <- ggsurvplot(fit5, fun = "cumhaz", pval = TRUE, conf.int = TRUE,
           risk.table = T, risk.table.y.text.col = TRUE, ylim=c(0,0.5), xscale="d_y", legend.labs = c("DES", "DCB"), xlab = "Years Since Index Procedure", ylab = "Probability of Incurring Composite Endpoint", palette = c("#fba30c", "#0077b8"), theme = "lancet", break.time.by	= 365.25, pval.coord = c(0,0.25), legend.title = "")

fit6 <- survfit(Surv(Composite_wMort_FU, Composite_wMort) ~ DCB_DES, data = df.match_TBif)
plot6 <- ggsurvplot(fit6, fun = "cumhaz", pval = TRUE, conf.int = TRUE,
           risk.table = T, risk.table.y.text.col = TRUE, ylim=c(0,0.5), xscale="d_y", legend.labs = c("DES", "DCB"), xlab = "Years Since Index Procedure", ylab = "Probability of Incurring Composite Endpoint w/Mort", palette = c("#fba30c", "#0077b8"), theme = "lancet", break.time.by	= 365.25, pval.coord = c(0,0.15), legend.title = "")

cairo_pdf(filename = "SensitivityTBif/CumHazPlots_TrueBif.pdf",
         width = 6, height = 6, onefile = T)
print(plot1, newpage = F)
print(plot2)
print(plot3)
print(plot4)
print(plot5)
print(plot6)
dev.off()

df.match_TBif <- df.match_All %>%
  filter(True_Bif == "No")

fit1<- survfit(Surv(Mortality_FU, Mortality) ~ DCB_DES, data = df.match_TBif)
plot1 <- ggsurvplot(fit1, fun = "cumhaz", pval = TRUE, conf.int = TRUE,
           risk.table = T, risk.table.y.text.col = TRUE, ylim=c(0,0.3), xscale="d_y", legend.labs = c("DES", "DCB"), xlab = "Years Since Index Procedure", ylab = "Probability of All-Cause Mortality", palette = c("#fba30c", "#0077b8"), theme = "lancet", break.time.by	= 365.25, pval.coord = c(0,0.1), legend.title = "") 

fit2<- survfit(Surv(CV_Mortality_FU, CV_Mortality) ~ DCB_DES, data = df.match_TBif)
plot2 <- ggsurvplot(fit2, fun = "cumhaz", pval = TRUE, conf.int = TRUE,
           risk.table = T, risk.table.y.text.col = TRUE, ylim=c(0,0.3), xscale="d_y", legend.labs = c("DES", "DCB"), xlab = "Years Since Index Procedure", ylab = "Probability of Cardiovascular Mortality", palette = c("#fba30c", "#0077b8"), theme = "lancet", break.time.by	= 365.25, pval.coord = c(0,0.1), legend.title = "")  

fit3<- survfit(Surv(TLR_FU, TLR) ~ DCB_DES, data = df.match_TBif)
plot3 <- ggsurvplot(fit3, fun = "cumhaz", pval = TRUE, conf.int = TRUE,
           risk.table = T, risk.table.y.text.col = TRUE, ylim=c(0,0.3), xscale="d_y", legend.labs = c("DES", "DCB"), xlab = "Years Since Index Procedure", ylab = "Probability of Incurring TLR", palette = c("#fba30c", "#0077b8"), theme = "lancet", break.time.by	= 365.25, pval.coord = c(0,0.1), legend.title = "")  

fit4<- survfit(Surv(TLR_MI_FU, TLR_MI) ~ DCB_DES, data = df.match_TBif)
plot4 <- ggsurvplot(fit4, fun = "cumhaz", pval = TRUE, conf.int = TRUE,
           risk.table = T, risk.table.y.text.col = TRUE, ylim=c(0,0.3), xscale="d_y", legend.labs = c("DES", "DCB"), xlab = "Years Since Index Procedure", ylab = "Probability of Incurring Target Lesion MI", palette = c("#fba30c", "#0077b8"), theme = "lancet", break.time.by	= 365.25, pval.coord = c(0,0.1), legend.title = "")  

fit5<- survfit(Surv(Composite_FU, Composite) ~ DCB_DES, data = df.match_TBif)
plot5 <- ggsurvplot(fit5, fun = "cumhaz", pval = TRUE, conf.int = TRUE,
           risk.table = T, risk.table.y.text.col = TRUE, ylim=c(0,0.5), xscale="d_y", legend.labs = c("DES", "DCB"), xlab = "Years Since Index Procedure", ylab = "Probability of Incurring Composite Endpoint", palette = c("#fba30c", "#0077b8"), theme = "lancet", break.time.by	= 365.25, pval.coord = c(0,0.25), legend.title = "")

fit6 <- survfit(Surv(Composite_wMort_FU, Composite_wMort) ~ DCB_DES, data = df.match_TBif)
plot6 <- ggsurvplot(fit6, fun = "cumhaz", pval = TRUE, conf.int = TRUE,
           risk.table = T, risk.table.y.text.col = TRUE, ylim=c(0,0.5), xscale="d_y", legend.labs = c("DES", "DCB"), xlab = "Years Since Index Procedure", ylab = "Probability of Incurring Composite Endpoint w/Mort", palette = c("#fba30c", "#0077b8"), theme = "lancet", break.time.by	= 365.25, pval.coord = c(0,0.15), legend.title = "")

cairo_pdf(filename = "SensitivityTBif/CumHazPlots_NOTTrueBif.pdf",
         width = 6, height = 6, onefile = T)
print(plot1, newpage = F)
print(plot2)
print(plot3)
print(plot4)
print(plot5)
print(plot6)
dev.off()

```

```{r Checking Assumptions for MV_Tables}
library(coxme)

data_bif_mv1 <- df.match_All %>%
  select(DCB_DES, Age, Sex, Presentation, True_Bif, PMHx_MI, PMHx_PCI, PMHx_AF, Heavy_Calc, Diffuse_Dx, Tortuosity, Tortuosity, denovo_VesselDiam, denovo_LesionLgth, Vessel_Tx, Mortality, Mortality_FU, CV_Mortality, CV_Mortality_FU, TLR, TLR_FU, TLR_MI, TLR_MI_FU, Composite, Composite_FU, Composite_wMort, Composite_wMort_FU, subclass) %>%
  drop_na() %>%
  mutate(subclass = as.numeric(subclass)) %>%
  mutate(Presentation = fct_relevel(Presentation, c("Stable Angina", "ACS", "STEMI")))

#res.cox_Mortality <- coxme(Surv(time = Mortality_FU, event = Mortality) ~ DCB_DES + Age+ Sex+ Presentation+ True_Bif+ PMHx_MI+ PMHx_PCI+ PMHx_AF+ Heavy_Calc+ Diffuse_Dx+ Tortuosity+ denovo_VesselDiam+ denovo_LesionLgth, + (1|subclass), data = data_bif_mv1)

res.cox_Comp <- coxme(Surv(time = Composite_FU, event = Composite) ~ DCB_DES + Age+ Sex+ Presentation+ Vessel_Tx+ True_Bif+ PMHx_MI+ PMHx_PCI+ PMHx_AF+ Heavy_Calc+ Diffuse_Dx+ Tortuosity +denovo_VesselDiam+ denovo_LesionLgth+ (1|subclass), data = data_bif_mv1)

res.cox_TLR <- coxme(Surv(time = TLR_FU, event = TLR) ~ DCB_DES + Age+ Sex+ Presentation+ Vessel_Tx+ True_Bif+ PMHx_MI+ PMHx_PCI+ PMHx_AF +Heavy_Calc+ Diffuse_Dx+ Tortuosity +denovo_VesselDiam+ denovo_LesionLgth+ (1|subclass), data = data_bif_mv1)

res.cox_TLRMI <- coxme(Surv(time = TLR_MI_FU, event = TLR_MI) ~ DCB_DES + Age+ Sex+ Presentation+ Vessel_Tx+ True_Bif+ PMHx_MI+ PMHx_PCI+ PMHx_AF + Heavy_Calc+ Diffuse_Dx+ Tortuosity +denovo_VesselDiam+ denovo_LesionLgth+ (1|subclass), data = data_bif_mv1)

res.cox_CVMortality <- coxme(Surv(time = CV_Mortality_FU, event = CV_Mortality) ~ DCB_DES + Age+ Sex+ Presentation+ Vessel_Tx+ True_Bif+ Heavy_Calc+ Diffuse_Dx+ Tortuosity + denovo_VesselDiam + denovo_LesionLgth+ (1|subclass), data = data_bif_mv1)

#res.cox_CompwMort <- coxme(Surv(time = Composite_wMort_FU, event = Composite_wMort) ~ DCB_DES + Age+ Sex+ Presentation+ True_Bif+ PMHx_MI+ PMHx_PCI+ PMHx_AF+ Heavy_Calc+ Diffuse_Dx+ Tortuosity +denovo_VesselDiam+ denovo_LesionLgth+ (1|subclass), data = data_bif_mv1)

#test.ph1 = cox.zph(res.cox_Mortality)
test.ph2 = cox.zph(res.cox_Comp) 
test.ph3 = cox.zph(res.cox_TLR)
test.ph4 = cox.zph(res.cox_TLRMI)
test.ph5 = cox.zph(res.cox_CVMortality)
#test.ph6 = cox.zph(res.cox_CompwMort)

#plot1 <- ggcoxzph(test.ph1)
plot2 <- ggcoxzph(test.ph2)
plot3 <- ggcoxzph(test.ph3)
plot4 <- ggcoxzph(test.ph4)
plot5 <- ggcoxzph(test.ph5)
# <- ggcoxzph(test.ph6)


cairo_pdf(filename = "CoxAssumptions/Assumptions.pdf",
         width = 30, height = 30, onefile = T)
#print(plot1, newpage = F)
print(plot2, newpage = F)
print(plot3)
print(plot4)
print(plot5)
#print(plot6)
dev.off()

```

```{r Tables for Cox ME}
tbl_Composite <- gtsummary::tbl_regression(res.cox_Comp,
                                   exponentiate = T) %>%
  gtsummary::bold_p() %>%
  gtsummary::modify_header(label = paste0("**Composite**", " (Multivariate)")) %>%
  gtsummary::as_gt()

tbl_TLR <- gtsummary::tbl_regression(res.cox_TLR,
                                   exponentiate = T) %>%
  gtsummary::bold_p() %>%
  gtsummary::modify_header(label = paste0("**TLR**", " (Multivariate)")) %>%
  gtsummary::as_gt()

tbl_TLRMI <- gtsummary::tbl_regression(res.cox_TLRMI,
                                   exponentiate = T) %>%
  gtsummary::bold_p() %>%
  gtsummary::modify_header(label = paste0("**TLR-MI**", " (Multivariate)")) %>%
  gtsummary::as_gt()

tbl_CVMort <- gtsummary::tbl_regression(res.cox_CVMortality,
                                   exponentiate = T) %>%
  gtsummary::bold_p() %>%
  gtsummary::modify_header(label = paste0("**CVMortality**", " (Multivariate)")) %>%
  gtsummary::as_gt()


gtsave(tbl_Composite, "MV_Tables/Composite_MV.html")
gtsave(tbl_TLR, "MV_Tables/PS_TLR_MV.html")
gtsave(tbl_TLRMI, "MV_Tables/TLRMI_MV.html")
gtsave(tbl_CVMort, "MV_Tables/CV_Mort_MV.html")

```

